//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolalindSolver.Core.App_LocalResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RolalindSolver.Core.App_LocalResourses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change current problem..
        /// </summary>
        public static string ChangeCurrentProblem {
            get {
                return ResourceManager.GetString("ChangeCurrentProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change server settings..
        /// </summary>
        public static string ChangeServerSettings {
            get {
                return ResourceManager.GetString("ChangeServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user settings..
        /// </summary>
        public static string ChangeUserSettings {
            get {
                return ResourceManager.GetString("ChangeUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear solved problems records..
        /// </summary>
        public static string ClearSolvedProblemsRecords {
            get {
                return ResourceManager.GetString("ClearSolvedProblemsRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid item index:.
        /// </summary>
        public static string PleaseEnterValidIndex {
            get {
                return ResourceManager.GetString("PleaseEnterValidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;{0}&apos; value:.
        /// </summary>
        public static string PleaseEnterValue {
            get {
                return ResourceManager.GetString("PleaseEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select problem for sending solution.
        /// </summary>
        public static string PleaseSelectProblem {
            get {
                return ResourceManager.GetString("PleaseSelectProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this value in config file? [Y] Yes / [N] No.
        /// </summary>
        public static string RememberValueRequest {
            get {
                return ResourceManager.GetString("RememberValueRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all solutions..
        /// </summary>
        public static string SendAllSolutions {
            get {
                return ResourceManager.GetString("SendAllSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all unsolved..
        /// </summary>
        public static string SendAllUnsolved {
            get {
                return ResourceManager.GetString("SendAllUnsolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send currently selected problem..
        /// </summary>
        public static string SendCurrentlySelected {
            get {
                return ResourceManager.GetString("SendCurrentlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be empty.
        /// </summary>
        public static string ValueShoulNotBeEmpty {
            get {
                return ResourceManager.GetString("ValueShoulNotBeEmpty", resourceCulture);
            }
        }
    }
}
